---
title: 'Animate.css Extension for Quarto'
format: html
---


## Using the extension

This extension provides support and shortcode to [animate.css](https://animate.style/).  
Animations are only available for HTML-based documents.
It provides an `{{{< animate >}}}` shortcode:

- Mandatory `<effect>` and `<text>`:
  ``` markdown
  {{{< animate <effect> "<text>" >}}}
  ```

- Optional `<delay=...>`, `<duration=...>`, and `<repeat=...>`:
  ``` markdown
  {{{< animate <effect> "<text>" <delay=...> <duration=...> <repeat=...> >}}}
  ```
  `<delay=...>` and `<duration=...>` are durations requiring unit, _e.g._, `1s` or `800ms`.  
  See <https://animate.style/> for more details.

For example:

| Shortcode                                                                  | Text                                                                   |
| -------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| `{{{< animate bounce "Some text" >}}}`                                     | {{< animate bounce "Some text" >}}                                     |
| `{{{< animate flip "Some text" repeat=2 >}}}`                              | {{< animate flip "Some text" repeat=2 >}}                              |
| `{{{< animate hinge "Some text" delay=3s duration=4s repeat=infinite >}}}` | {{< animate hinge "Some text" delay=1s duration=2s repeat=infinite >}} |

## Advanced

The following won't work:

```markdown
{{{< animate bounce "[HTML](https://m.canouil.fr/quarto-animate/)" >}}}
```

But this will:

```markdown
[[HTML](https://m.canouil.fr/quarto-animate/)]{.animate__animated .animate__bounce style="display:inline-block;"}
```

[[HTML](https://m.canouil.fr/quarto-animate/)]{.animate__animated .animate__bounce style="display:inline-block;"}

Or:

```markdown
::: {.animate__animated .animate__bounce}
[HTML](https://m.canouil.fr/quarto-animate/)
:::
```

::: {.animate__animated .animate__bounce}
[HTML](https://m.canouil.fr/quarto-animate/)
:::

## Available effects:

### Attention seekers

- `bounce` {{< animate bounce "bounce" repeat=infinite duration=4s >}}
- `flash` {{< animate flash "flash" repeat=infinite duration=4s >}}
- `pulse` {{< animate pulse "pulse" repeat=infinite duration=4s >}}
- `rubberBand` {{< animate rubberBand "rubberBand" repeat=infinite duration=4s >}}
- `shakeX` {{< animate shakeX "shakeX" repeat=infinite duration=4s >}}
- `shakeY` {{< animate shakeY "shakeY" repeat=infinite duration=4s >}}
- `headShake` {{< animate headShake "headShake" repeat=infinite duration=4s >}}
- `swing` {{< animate swing "swing" repeat=infinite duration=4s >}}
- `tada` {{< animate tada "tada" repeat=infinite duration=4s >}}
- `wobble` {{< animate wobble "wobble" repeat=infinite duration=4s >}}
- `jello` {{< animate jello "jello" repeat=infinite duration=4s >}}
- `heartBeat` {{< animate heartBeat "heartBeat" repeat=infinite duration=4s >}}

### Back entrances

- `backInDown` {{< animate backInDown "backInDown" repeat=infinite duration=4s >}}
- `backInLeft` {{< animate backInLeft "backInLeft" repeat=infinite duration=4s >}}
- `backInRight` {{< animate backInRight "backInRight" repeat=infinite duration=4s >}}
- `backInUp` {{< animate backInUp "backInUp" repeat=infinite duration=4s >}}

### Back exits

- `backOutDown` {{< animate backOutDown "backOutDown" repeat=infinite duration=4s >}}
- `backOutLeft` {{< animate backOutLeft "backOutLeft" repeat=infinite duration=4s >}}
- `backOutRight` {{< animate backOutRight "backOutRight" repeat=infinite duration=4s >}}
- `backOutUp` {{< animate backOutUp "backOutUp" repeat=infinite duration=4s >}}

### Bouncing entrances

- `bounceIn` {{< animate bounceIn "bounceIn" repeat=infinite duration=4s >}}
- `bounceInDown` {{< animate bounceInDown "bounceInDown" repeat=infinite duration=4s >}}
- `bounceInLeft` {{< animate bounceInLeft "bounceInLeft" repeat=infinite duration=4s >}}
- `bounceInRight` {{< animate bounceInRight "bounceInRight" repeat=infinite duration=4s >}}
- `bounceInUp` {{< animate bounceInUp "bounceInUp" repeat=infinite duration=4s >}}

### Bouncing exits

- `bounceOut` {{< animate bounceOut "bounceOut" repeat=infinite duration=4s >}}
- `bounceOutDown` {{< animate bounceOutDown "bounceOutDown" repeat=infinite duration=4s >}}
- `bounceOutLeft` {{< animate bounceOutLeft "bounceOutLeft" repeat=infinite duration=4s >}}
- `bounceOutRight` {{< animate bounceOutRight "bounceOutRight" repeat=infinite duration=4s >}}
- `bounceOutUp` {{< animate bounceOutUp "bounceOutUp" repeat=infinite duration=4s >}}

### Fading entrances

- `fadeIn` {{< animate fadeIn "fadeIn" repeat=infinite duration=4s >}}
- `fadeInDown` {{< animate fadeInDown "fadeInDown" repeat=infinite duration=4s >}}
- `fadeInDownBig` {{< animate fadeInDownBig "fadeInDownBig" repeat=infinite duration=4s >}}
- `fadeInLeft` {{< animate fadeInLeft "fadeInLeft" repeat=infinite duration=4s >}}
- `fadeInLeftBig` {{< animate fadeInLeftBig "fadeInLeftBig" repeat=infinite duration=4s >}}
- `fadeInRight` {{< animate fadeInRight "fadeInRight" repeat=infinite duration=4s >}}
- `fadeInRightBig` {{< animate fadeInRightBig "fadeInRightBig" repeat=infinite duration=4s >}}
- `fadeInUp` {{< animate fadeInUp "fadeInUp" repeat=infinite duration=4s >}}
- `fadeInUpBig` {{< animate fadeInUpBig "fadeInUpBig" repeat=infinite duration=4s >}}
- `fadeInTopLeft` {{< animate fadeInTopLeft "fadeInTopLeft" repeat=infinite duration=4s >}}
- `fadeInTopRight` {{< animate fadeInTopRight "fadeInTopRight" repeat=infinite duration=4s >}}
- `fadeInBottomLeft` {{< animate fadeInBottomLeft "fadeInBottomLeft" repeat=infinite duration=4s >}}
- `fadeInBottomRight` {{< animate fadeInBottomRight "fadeInBottomRight" repeat=infinite duration=4s >}}

### Fading exits

- `fadeOut` {{< animate fadeOut "fadeOut" repeat=infinite duration=4s >}}
- `fadeOutDown` {{< animate fadeOutDown "fadeOutDown" repeat=infinite duration=4s >}}
- `fadeOutDownBig` {{< animate fadeOutDownBig "fadeOutDownBig" repeat=infinite duration=4s >}}
- `fadeOutLeft` {{< animate fadeOutLeft "fadeOutLeft" repeat=infinite duration=4s >}}
- `fadeOutLeftBig` {{< animate fadeOutLeftBig "fadeOutLeftBig" repeat=infinite duration=4s >}}
- `fadeOutRight` {{< animate fadeOutRight "fadeOutRight" repeat=infinite duration=4s >}}
- `fadeOutRightBig` {{< animate fadeOutRightBig "fadeOutRightBig" repeat=infinite duration=4s >}}
- `fadeOutUp` {{< animate fadeOutUp "fadeOutUp" repeat=infinite duration=4s >}}
- `fadeOutUpBig` {{< animate fadeOutUpBig "fadeOutUpBig" repeat=infinite duration=4s >}}
- `fadeOutTopLeft` {{< animate fadeOutTopLeft "fadeOutTopLeft" repeat=infinite duration=4s >}}
- `fadeOutTopRight` {{< animate fadeOutTopRight "fadeOutTopRight" repeat=infinite duration=4s >}}
- `fadeOutBottomRight` {{< animate fadeOutBottomRight "fadeOutBottomRight" repeat=infinite duration=4s >}}
- `fadeOutBottomLeft` {{< animate fadeOutBottomLeft "fadeOutBottomLeft" repeat=infinite duration=4s >}}

### Flippers

- `flip` {{< animate flip "flip" repeat=infinite duration=4s >}}
- `flipInX` {{< animate flipInX "flipInX" repeat=infinite duration=4s >}}
- `flipInY` {{< animate flipInY "flipInY" repeat=infinite duration=4s >}}
- `flipOutX` {{< animate flipOutX "flipOutX" repeat=infinite duration=4s >}}
- `flipOutY` {{< animate flipOutY "flipOutY" repeat=infinite duration=4s >}}

### Lightspeed

- `lightSpeedInRight` {{< animate lightSpeedInRight "lightSpeedInRight" repeat=infinite duration=4s >}}
- `lightSpeedInLeft` {{< animate lightSpeedInLeft "lightSpeedInLeft" repeat=infinite duration=4s >}}
- `lightSpeedOutRight` {{< animate lightSpeedOutRight "lightSpeedOutRight" repeat=infinite duration=4s >}}
- `lightSpeedOutLeft` {{< animate lightSpeedOutLeft "lightSpeedOutLeft" repeat=infinite duration=4s >}}

### Rotating entrances

- `rotateIn` {{< animate rotateIn "rotateIn" repeat=infinite duration=4s >}}
- `rotateInDownLeft` {{< animate rotateInDownLeft "rotateInDownLeft" repeat=infinite duration=4s >}}
- `rotateInDownRight` {{< animate rotateInDownRight "rotateInDownRight" repeat=infinite duration=4s >}}
- `rotateInUpLeft` {{< animate rotateInUpLeft "rotateInUpLeft" repeat=infinite duration=4s >}}
- `rotateInUpRight` {{< animate rotateInUpRight "rotateInUpRight" repeat=infinite duration=4s >}}

### Rotating exits

- `rotateOut` {{< animate rotateOut "rotateOut" repeat=infinite duration=4s >}}
- `rotateOutDownLeft` {{< animate rotateOutDownLeft "rotateOutDownLeft" repeat=infinite duration=4s >}}
- `rotateOutDownRight` {{< animate rotateOutDownRight "rotateOutDownRight" repeat=infinite duration=4s >}}
- `rotateOutUpLeft` {{< animate rotateOutUpLeft "rotateOutUpLeft" repeat=infinite duration=4s >}}
- `rotateOutUpRight` {{< animate rotateOutUpRight "rotateOutUpRight" repeat=infinite duration=4s >}}

### Specials

- `hinge` {{< animate hinge "hinge" repeat=infinite duration=4s >}}
- `jackInTheBox` {{< animate jackInTheBox "jackInTheBox" repeat=infinite duration=4s >}}
- `rollIn` {{< animate rollIn "rollIn" repeat=infinite duration=4s >}}
- `rollOut` {{< animate rollOut "rollOut" repeat=infinite duration=4s >}}

### Zooming entrances

- `zoomIn` {{< animate zoomIn "zoomIn" repeat=infinite duration=4s >}}
- `zoomInDown` {{< animate zoomInDown "zoomInDown" repeat=infinite duration=4s >}}
- `zoomInLeft` {{< animate zoomInLeft "zoomInLeft" repeat=infinite duration=4s >}}
- `zoomInRight` {{< animate zoomInRight "zoomInRight" repeat=infinite duration=4s >}}
- `zoomInUp` {{< animate zoomInUp "zoomInUp" repeat=infinite duration=4s >}}

### Zooming exits

- `zoomOut` {{< animate zoomOut "zoomOut" repeat=infinite duration=4s >}}
- `zoomOutDown` {{< animate zoomOutDown "zoomOutDown" repeat=infinite duration=4s >}}
- `zoomOutLeft` {{< animate zoomOutLeft "zoomOutLeft" repeat=infinite duration=4s >}}
- `zoomOutRight` {{< animate zoomOutRight "zoomOutRight" repeat=infinite duration=4s >}}
- `zoomOutUp` {{< animate zoomOutUp "zoomOutUp" repeat=infinite duration=4s >}}

### Sliding entrances

- `slideInDown` {{< animate slideInDown "slideInDown" repeat=infinite duration=4s >}}
- `slideInLeft` {{< animate slideInLeft "slideInLeft" repeat=infinite duration=4s >}}
- `slideInRight` {{< animate slideInRight "slideInRight" repeat=infinite duration=4s >}}
- `slideInUp` {{< animate slideInUp "slideInUp" repeat=infinite duration=4s >}}

### Sliding exits

- `slideOutDown` {{< animate slideOutDown "slideOutDown" repeat=infinite duration=4s >}}
- `slideOutLeft` {{< animate slideOutLeft "slideOutLeft" repeat=infinite duration=4s >}}
- `slideOutRight` {{< animate slideOutRight "slideOutRight" repeat=infinite duration=4s >}}
- `slideOutUp` {{< animate slideOutUp "slideOutUp" repeat=infinite duration=4s >}}
