name: Deploy GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: mcanouil/quarto-extensions-actions/.github/workflows/deploy.yml@main
        with:
          formats: "html"
          tinytex: false
          version: "release"
