name: Deploy GitHub Pages

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Quarto version"
        required: false
        default: "release"
        type: string
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: mcanouil/quarto-extensions-actions/.github/workflows/deploy.yml@main
        with:
          formats: "html"
          tinytex: "${{ github.event.inputs.tinytex }}"
          version: false
