name: Release Quarto Extension

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Version"
        required: false
        default: "patch"
        options:
          - "patch"
          - "minor"
          - "major"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: mcanouil/quarto-extensions-actions/.github/workflows/release.yml@main
        with:
          version: "${{ github.event.inputs.version }}"
